1.TO DISPLAY MAXIMUM SALARY WITH FIRST_NAME:
      
      SELECT FIRST_NAME FROM EMPLOYEES WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES);
	  
2.TO DISPLAY USERNAME IN YOUR DATABASE:

     SELECT USERNAME FROM ALL_USERS;
	 
3.TO DISPLAY EMPLOYEES WORKING FOR THE PAST 5 YEARS:

     SELECT FIRST_NAME FROM EMPLOYEES WHERE(TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(HIRE_DATE,'YYYY'))>5;
	 
4.TO DISPLAY THE EMPLOYEES JOINED BEFORE 31-JUN-90 AND AFTER 30-DEC-90:

    SELECT FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE (TO_CHAR(HIRE_DATE,'DD-MM-YY')<'31-JUN-90' AND TO_CHAR(HIRE_DATE,'DD-MM-YY')<'31-DEC-90');
	
5.TO DISPLAY THE NAMES OF ALL TABLES FROM CURRENT USER:

    SELECT TNAME FROM TAB;
	
6.TO DISPLAY THE NAMES OF EMPLOYEE AND THEIR MAANAGER:

     SELECT E.EMPLOYEE_ID,E.FIRST_NAME,M.FIRST_NAME,E.MANAGER_ID FROM EMPLOYEES E,EMPLOYEES M WHERE E.MANAGER_ID=M.EMPLOYEE_ID ;

7.TO DISPLAY THE  FIRST NAME OF EMPLOYEES WHO ARE ALL WORKING AS MANAGER:
     
     SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID IN(SELECT DISTINCT MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL);
	 
8.TO DISPLAY EMPLOYEES WHO ARE ALL GETTING SALARY MORE THAN THEIR MANAGER SALARY:

     SELECT E.EMPLOYEE_ID,E.FIRST_NAME,M.FIRST_NAME,E.SALARY,M.SALARY FROM EMPLOYEES E,EMPLOYEES M 
     WHERE E.MANAGER_ID=M.EMPLOYEE_ID AND E.SALARY>M.SALARY;
	 
9.TO DISPLAY EMPLOYEES HIRED BEFORE THEIR MANAGER

     SELECT E.EMPLOYEE_ID,E.FIRST_NAME,M.FIRST_NAME,E.SALARY,M.SALARY FROM EMPLOYEES E,EMPLOYEES M 
	 WHERE E.MANAGER_ID=M.EMPLOYEE_ID AND E.HIRE_DATE<M.HIRE_DATE;
     
10.TO DISPLAY THE NEXT_DAY IE..NEXT FRIDAY,NEXT SATURDAY:

     SELECT NEXT_DAY(SYSDATE,'SATURDAY')FROM DUAL	 
	  NEXT_DAY(
      ---------
      12-JAN-19
	  
	 SELECT NEXT_DAY(TO_DATE('01-01-2019','DD-MM-YYYY'),'FRIDAY')FROM DUAL;
	 
11.TO DISPLAY  LAST DAY OF A MONTH

      SELECT LAST_DAY(SYSDATE)FROM DUAL;
	  
	  SELECT LAST_DAY('01-FEB-19') FROM DUAL;
	  
12.TO DISPLAY THE EMPLOYEE DETAILS WHO DONOT HAVE MANAGER:
     
	 SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
	 
13.TO DISPLAY THE PARTICULAR ROWID AND ITS DETAILS:

	 SELECT * FROM EMPLOYEES WHERE ROWNUM<11 MINUS SELECT * FROM EMPLOYEES WHERE ROWNUM<10;

14.TO DISPLAY THE ROWID

      SELECT ROWID,FIRST_NAME FROM EMPLOYEES WHERE ROWNUM<11 ;

15.TO DELETE THE DUPLICATE RECORDS USING ROWID:

      DELETE FROM EMP WHERE ROWID NOT IN(SELECT MIN(ROWID) FROM EMP GROUP BY FIRST_NAME);	  

16.TO DISPLAY ODD ROWS FROM THE TABLE

	  SELECT * FROM (SELECT ROWNUM RN,E.* FROM EMPLOYEES E) WHERE MOD(RN,2)=1;
	  
17.TO DISPLAY EVEN ROWS FROM THE TABLE	 

       SELECT * FROM (SELECT ROWNUM RN,E.* FROM EMPLOYEES E) WHERE MOD(RN,2)=0;
	   
18.LAST DATE AND FIRST DATE OF PREVIOUS MONTH

       
SELECT TO_DATE((TO_CHAR(last_day('01-FEB-2019'),'MM')-1),'MM') ||' ' || LAST_DAY(TO_DATE((TO_CHAR(last_day('01-FEB-2019'),'MM')-1),'MM')) FROM DUAL;















2.TO DISPLAY NTH MAXIMUM SALARY

----USING ROWNUM:
           SELECT * FROM(SELECT ROWNUM RNK,SALARY FROM (SELECT SALARY FROM EMPLOYEES ORDER BY SALARY DESC) )WHERE RNK=&N;
		 
		 
----USING DENSE_RANK():
           SELECT DISTINCT SALARY FROM (SELECT DENSE_RANK() OVER(ORDER BY SALARY DESC) "DR",SALARY FROM EMPLOYEES) WHERE DR=&N;
		   
		   
----USING SUBQUERY:
            
          SELECT * FROM EMPLOYEES X WHERE &N=(SELECT COUNT(DISTINCT Y.SALARY) FROM EMPLOYEES Y WHERE Y.SALARY>=X.SALARY);
		  
		  

		   
		   
		   
